export const GET_TASK_LIST = 'GET_TASK_LIST'
export const DELETE_TASK = 'DELETE_TASK'
export const ADD_TASK = 'ADD_TASK'
export const GET_TASK = 'GET_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const GET_ALL_TASKS = 'GET_ALL_TASKS'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
